FROM alpine:3.18
RUN apk add --no-cache curl bash git openssh-client
# Inštalácia Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl && mv kubectl /usr/local/bin/

# Skopírovanie tvojho projektu
COPY . /app
WORKDIR /app
COPY bootstrap.sh /usr/local/bin/bootstrap.sh

ENTRYPOINT ["/usr/local/bin/bootstrap.sh"]
