#!/bin/bash
echo "=== MANUÁLNE VYTVORENIE DASHBOARDU V KIBANE ==="
echo ""
echo "Postupujte podľa týchto krokov v Kibana UI:"
echo "----------------------------------------"
echo "1. Otvorte Kibanu: http://kibana.34.89.208.249.nip.io"
echo "2. Ak ste ešte nenastavili index pattern, choďte do:"
echo "   Stack Management → Index Patterns → Create index pattern"
echo "   - Name: logs-lamp-*"
echo "   - Time field: @timestamp"
echo "   → Create index pattern"
echo ""
echo "3. Vytvorenie vizualizácie:"
echo "   - Kliknite na 'Visualize Library' (vľavo dole)"
echo "   - 'Create visualization' → 'Aggregation based' → 'Line chart' (alebo 'Bar chart')"
echo "   - Vyberte index pattern 'logs-lamp-*'"
echo "   - V horizontálnej osi:"
echo "     * Aggregation: Date Histogram"
echo "     * Field: @timestamp"
echo "     * Interval: Auto"
echo "   - Kliknite 'Update'"
echo "   - Uložte ako 'Logs over time'"
echo ""
echo "4. Vytvorenie dashboardu:"
echo "   - Kliknite na 'Dashboard' (vľavo hore)"
echo "   - 'Create dashboard'"
echo "   - 'Add' → vyberte 'Logs over time'"
echo "   - Uložte dashboard ako 'Logs Dashboard'"
echo ""
echo "5. Pre automatické vytvorenie pomocou API spustite:"
echo "   ./create-kibana-dashboard.sh (ak ste tak ešte neurobili)"
echo ""
echo "=== HOTOVO ==="
