apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: '2026-02-26T14:26:16Z'
    name: default
    namespace: ingress-nginx
    resourceVersion: '187616'
    uid: 035f68c8-6244-4964-b26a-aca130cdcacd
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.8.1"},"name":"ingress-nginx","namespace":"ingress-nginx"}}

        '
    creationTimestamp: '2026-02-26T14:26:16Z'
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.8.1
    name: ingress-nginx
    namespace: ingress-nginx
    resourceVersion: '187614'
    uid: 6e121cf7-5f64-4874-bd91-b5db65ca54d3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"admission-webhook","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.8.1"},"name":"ingress-nginx-admission","namespace":"ingress-nginx"}}

        '
    creationTimestamp: '2026-02-26T14:26:16Z'
    labels:
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.8.1
    name: ingress-nginx-admission
    namespace: ingress-nginx
    resourceVersion: '187615'
    uid: 7d91308a-9f6d-473e-b58b-346a99f4b7b3
kind: List
metadata: {}
