apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-nginx-ingress-access","namespace":"web-stack"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{},"policyTypes":["Ingress"]}}

        '
    creationTimestamp: '2026-02-25T21:23:27Z'
    generation: 1
    name: allow-nginx-ingress-access
    namespace: web-stack
    resourceVersion: '49818'
    uid: 8a59b5c2-01dd-4380-96ed-c1632895b2f9
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata: {}
