apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
  namespace: lamp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
      - name: phpfpm
        image: php:fpm-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i 's/;pm.status_path = \/status/pm.status_path = \/status/g' /usr/local/etc/php-fpm.d/www.conf
            php-fpm
        ports:
        - containerPort: 9000
      - name: apache-exporter
        image: bitnami/apache-exporter:latest
        args: ["--scrape_uri", "http://localhost/server-status?auto"]
        ports:
        - containerPort: 9117
      - name: phpfpm-exporter
        image: bitnami/php-fpm-exporter:latest
        env:
        - name: PHP_FPM_SCRAPE_URI
          value: "tcp://localhost:9000/status"
        ports:
        - containerPort: 9253
