apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-nginx-ingress-access","namespace":"web"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{},"policyTypes":["Ingress"]}}
    creationTimestamp: "2026-02-25T21:23:27Z"
    generation: 1
    name: allow-nginx-ingress-access
    namespace: web
    resourceVersion: "49817"
    uid: 488275b6-98ce-45ee-a88d-ddfeef374964
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata:
  resourceVersion: ""
