apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: '2026-02-25T17:38:58Z'
    name: default
    namespace: web
    resourceVersion: '22905'
    uid: 779f633d-cca9-4988-bffe-aa286a489a1a
kind: List
metadata: {}
