apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: instance-20260225-131727
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-02-27T11:19:10Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: rabbitmq
      app.kubernetes.io/name: rabbitmq
    name: data-rabbitmq-0
    namespace: online-retail
    resourceVersion: "280790"
    uid: e14a49b5-5a14-480e-a4f3-a416427245e9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-e14a49b5-5a14-480e-a4f3-a416427245e9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      cnpg.io/nodeSerial: "1"
      cnpg.io/operatorVersion: 1.28.1
      cnpg.io/pvcStatus: ready
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: instance-20260225-131727
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-02-27T07:09:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      cnpg.io/cluster: postgres
      cnpg.io/instanceName: postgres-1
      cnpg.io/instanceRole: primary
      cnpg.io/pvcRole: PG_DATA
      role: primary
    name: postgres-1
    namespace: online-retail
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: postgres
      uid: 5340d90b-08e3-4bd1-b0cd-015e7999f484
    resourceVersion: "261865"
    uid: 5b55ce19-cfed-4d5d-ae4c-8628d0c8c6f7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-5b55ce19-cfed-4d5d-ae4c-8628d0c8c6f7
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
