apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-grafana-to-prometheus","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"podSelector":{"matchLabels":{"app":"grafana"}}}],"ports":[{"port":9090,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"app":"prometheus"}},"policyTypes":["Ingress"]}}

        '
    creationTimestamp: '2026-02-26T08:54:41Z'
    generation: 1
    name: allow-grafana-to-prometheus
    namespace: monitoring
    resourceVersion: '147896'
    uid: 3e930718-02fe-4f3b-b827-ae859f03fed8
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app: grafana
      ports:
      - port: 9090
        protocol: TCP
    podSelector:
      matchLabels:
        app: prometheus
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-ingress-to-prometheus","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{"matchLabels":{"app":"prometheus"}},"policyTypes":["Ingress"]}}

        '
    creationTimestamp: '2026-02-25T21:17:19Z'
    generation: 1
    name: allow-ingress-to-prometheus
    namespace: monitoring
    resourceVersion: '49103'
    uid: 81d5fea2-4e34-427f-b728-bd2e2670bc75
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector:
      matchLabels:
        app: prometheus
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-nginx-ingress-access","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{},"policyTypes":["Ingress"]}}

        '
    creationTimestamp: '2026-02-25T21:23:27Z'
    generation: 1
    name: allow-nginx-ingress-access
    namespace: monitoring
    resourceVersion: '49814'
    uid: 9783ea5b-778f-4010-8660-53006a822e3c
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata: {}
