apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-grafana-to-prometheus","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"podSelector":{"matchLabels":{"app":"grafana"}}}],"ports":[{"port":9090,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"app":"prometheus"}},"policyTypes":["Ingress"]}}

        '
    name: allow-grafana-to-prometheus
    namespace: monitoring
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app: grafana
      ports:
      - port: 9090
        protocol: TCP
    podSelector:
      matchLabels:
        app: prometheus
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-ingress-to-prometheus","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{"matchLabels":{"app":"prometheus"}},"policyTypes":["Ingress"]}}

        '
    name: allow-ingress-to-prometheus
    namespace: monitoring
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector:
      matchLabels:
        app: prometheus
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-nginx-ingress-access","namespace":"monitoring"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"ingress-nginx"}}}]}],"podSelector":{},"policyTypes":["Ingress"]}}

        '
    name: allow-nginx-ingress-access
    namespace: monitoring
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata: {}
