apiVersion: v1
kind: Namespace
metadata:
  name: lamp
---
apiVersion: v1
kind: Service
metadata:
  name: apache-php
  namespace: lamp
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: apache-php
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: lamp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: apache.34.159.144.113.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-php
                port:
                  number: 80
