apiVersion: v1
kind: Namespace
metadata:
  name: lamp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index
  namespace: lamp
data:
  index.php: "<h1>🚀 GitOps Rebirth: Automatika funguje!</h1><?php phpinfo(); ?>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
  namespace: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
        - name: apache
          image: php:8.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /var/www/html/index.php
              subPath: index.php
      volumes:
        - name: web-content
          configMap:
            name: apache-index
---
apiVersion: v1
kind: Service
metadata:
  name: apache-php
  namespace: lamp
spec:
  selector:
    app: apache-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: lamp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "apache.34.159.144.113.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-php
                port:
                  number: 80
