apiVersion: v1
kind: Namespace
metadata:
  name: lamp
---
apiVersion: v1
kind: Service
metadata:
  name: apache-php
  namespace: lamp
spec:
  selector:
    app: apache-php
  ports:
    - name: http
      port: 80
    - name: apache-metrics
      port: 9117
    - name: php-metrics
      port: 9253
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: lamp
spec:
  selector:
    app: postgresql
  ports:
    - name: postgres
      port: 5432
    - name: postgres-metrics
      port: 9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              value: "admin123"
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter
          ports:
            - containerPort: 9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
  namespace: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
        - name: apache
          image: php:8.2-apache
          ports:
            - containerPort: 80
        - name: apache-exporter
          image: lusotycoon/apache-exporter
          ports:
            - containerPort: 9117
        - name: phpfpm-exporter
          image: hipages/php-fpm_exporter
          ports:
            - containerPort: 9253
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: lamp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "apache.34.159.144.113.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-php
                port:
                  number: 80
