apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
  namespace: lamp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
      - name: phpfpm
        image: php:fpm-alpine
        env:
        # Tieto mená premenných sa musia zhodovať s tým, čo hľadá tvoj PHP kód
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123" # <--- SEM DAJ SVOJE SKUTOČNÉ HESLO
        ports:
        - containerPort: 9000
